### ISSUE TITLE
Django: Add data from From to Database(sqlite3)

### ISSUE THREAD

**Issue by sohan-k** [sohan-k/kklife#1]
Send a post request to /joinnow and add the data from the form to the database, creating an appropriate model.

**Comment by navi532** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by sohan-k** [comment]
Sure assigned to you @navi532

**Comment by SoumyaRanjanNaik** [comment]
Could you please elaborate so that we can know for which model do we need to do it ?
