### ISSUE TITLE
Create UI for cards, showing info about people ( create demo )

### ISSUE THREAD

**Issue by sohan-k** [sohan-k/kklife#2]
Create a profile card in bootstrap, html, css to show profile of people in kklife/templates/kklife/team.html

**Comment by coderburhan** [comment]
Can I Contribute?

**Comment by coderburhan** [comment]
I would like to conrtibute to this project ... would you assign me to it?

**Comment by sohan-k** [comment]
Sure! Assigned to you @coderburhan

**Comment by Geeky-star** [comment]
Hey, can I also contribute to this project?

**Comment by Deepakmukka1** [comment]
I would like to conrtibute to this project ... would you assign me to it?

**Comment by sohan-k** [comment]
@Geeky-star @Deepakmukka1 you can check out other issues

**Comment by sohan-k** [comment]
Opened at #4
