### ISSUE TITLE
Create UI template for blog 

### ISSUE THREAD

**Issue by sohan-k** [sohan-k/kklife#5]
Add UI template for showing a blog, design should be responsive and should work with the existing Django project. Put your files in kklife/template/kklife/

**Comment by purnima143** [comment]
Can I work on this issue?

**Comment by sohan-k** [comment]
Sure @purnima143 , just make it compatible with existing code and should work on Django server

**Comment by azizamukhamedova** [comment]
I have updated your blog model. If you want I can work on this issue.

**Comment by sohan-k** [comment]
If @purnima143 does not want to do, then @azizamukhamedova can surely do.

**Comment by purnima143** [comment]
@sohan-k  I am working on this issue.

**Comment by sohan-k** [comment]
Okay

**Comment by purnima143** [comment]
@sohan-k  I made a PR for this issue, kindly check it.

**Comment by sohan-k** [comment]
#10
