### ISSUE TITLE
Create model for Blogs

### ISSUE THREAD

**Issue by sohan-k** [sohan-k/kklife#6]
Create a model for blogs in Django so to add it to the database.

**Comment by SuvamPrasd** [comment]
I would like to work on this issue @sohan-k

**Comment by sohan-k** [comment]
Sure, assigned to you @SuvamPrasd

**Comment by azizamukhamedova** [comment]
can you assign me, I will do it faster

**Comment by SuvamPrasd** [comment]
Sorry, @sohan-k can you please assign this issue to @azizamukhamedova

**Comment by azizamukhamedova** [comment]
do you want other users be able to create blogs or you(admin) will be the only person who can create blogs?

**Comment by sohan-k** [comment]
Admin should create blogs only

**Comment by azizamukhamedova** [comment]
ok, thank you

**Comment by sohan-k** [comment]
Closed at #8
